version: "3.8"
services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TELETHON_API_ID=${TELETHON_API_ID}
      - TELETHON_API_HASH=${TELETHON_API_HASH}
    volumes:
      - ./data:/app/data
